apiVersion: apps/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: api-go
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: api-go
    spec:
      containers:
      - name: api-go
        # Run this image
        image: mrmendes/api-alpine-go:1.0
        ports:
        - containerPort: 8080